

problem1a: problem1a.cpp 
	g++ -g -Wall -std=c++11 -o problem1a problem1a.cpp

problem1b: problem1b.cpp
	g++ -g -Wall -std=c++11 -o problem1b problem1b.cpp

pa1: problem1a problem1b 

clean:
	rm -f pa1 *.o
	rm -f problem1a